spring:
  flyway:
    enabled: false
  application:
    name: following-service
  #ORACLE Universal Connection Pool (UCP) PROPERTIES
  datasource:
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: conPoolProd
      sql-for-validate-connection: select * from dual
      initial-pool-size: 1
      min-pool-size: 1
      max-pool-size: 10
    #ORACLE DATABASE - CONNECTION DETAILS
    #url: jdbc:oracle:thin:@//[hostname]:[port]/[DB service/name]
    #url: jdbc:oracle:thin:@[HOST][:PORT]:SID
    url: jdbc:oracle:thin:@localhost:PORT:SID
    username: username
    password: password