spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:oracle:21-slim-faststart:///pdb1
    username: test_user
    password: 123
  flyway:
    enabled: true
    locations: classpath:db/migration/