CREATE TABLE USERS(
    USER_ID NUMBER NOT NULL,
    USER_NAME VARCHAR2(10) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR2(15) NOT NULL,
    LAST_NAME VARCHAR2(15) NOT NULL,
    PASSWORD VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    REGISTRATION_DATE TIMESTAMP NOT NULL,

    CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);
CREATE TABLE FOLLOWS(
    FOLLOWER_ID NUMBER NOT NULL,
    FOLLOWED_ID NUMBER NOT NULL,
    FOLLOW_DATE TIMESTAMP NOT NULL,

    CONSTRAINT PK_FOLLOWS PRIMARY KEY (FOLLOWER_ID, FOLLOWED_ID),
    CONSTRAINT FK_FOLLOWER FOREIGN KEY (FOLLOWER_ID)
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_FOLLOWED FOREIGN KEY (FOLLOWED_ID)
        REFERENCES USERS(USER_ID) ON DELETE CASCADE
);
CREATE SEQUENCE user_pk_gen;